from .bass import Bass
from .copperhead import Copperhead
from .dolphin import Dolphin
from .donkey import Donkey
from .goat import Goat
from .goldfish import Goldfish
from .grub import Grub
from .horse import Horse
from .llama import Llama
from .pig import Pig
from .shark import Shark
from .slug import Slug
from .snail import Snail
from .whale import Whale
from .worm import Worm
from .goose import Goose
